# Generated by Django 4.2.6 on 2023-11-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_musicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentos',
            old_name='nombre',
            new_name='instrumento',
        ),
    ]
